### ISSUE TITLE
Error when using envlogger::init(): 'called `Result::unwrap()` on an `Err` value: SetLoggerError(())'

### ISSUE THREAD

**Issue by sotrh** [gfx-rs/subscriber#2]
I'm working on integrating WebGPU with the Nuxt framework, and I ran into this error. It occurs when I call `envlogger::init()` in my `main()` function.

Here's the log output

```
[2020-10-15T03:08:57Z INFO  winit::platform_impl::platform::x11::window] Guessed window scale factor: 1
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SetLoggerError(())', /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-subscriber-0.1.0/src/lib.rs:52:36
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1269
  14: core::result::Result<T,E>::unwrap
             at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:1005
  15: wgpu_subscriber::initialize_default_subscriber
             at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-subscriber-0.1.0/src/lib.rs:52
  16: nuxt_wgpu::main
             at src/main.rs:63
  17: std::rt::lang_start::{{closure}}
             at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  20: std::panicking::try
             at src/libstd/panicking.rs:325
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  23: std::rt::lang_start
             at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  24: main
  25: __libc_start_main
  26: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by cwfitzgerald** [comment]
This is a (perhaps poorly described) error signaling that the `log` based logger couldn't be set because something else got there first. wgpu-subscriber is currently fairly inflexible, so there's no way to turn the `log` handler off if you want another logger in place. I need to do a pass on this crate to smooth out some rough edges and make it a bit more user friendly.

**Comment by sotrh** [comment]
Does the `log` macro work as intended if I don't set my own logger?

**Comment by cwfitzgerald** [comment]
If you turn on wgpu-subscriber, the normal log macros will work, though not have any module information.

**Comment by sotrh** [comment]
Ok, good to know.

What would I need to change in the crate to be able to use my own logger?
